image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# Cache and keep downloaded dependencies between CI pipelines
cache:
  key: maven-build
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - cd game
    - mvn compile

test:
  stage: test
  script:
    - cd game
    - mvn test

# Documentation
#pages:
#  stage: deploy
#  script:
#    - cd game
#    - mvn javadoc:javadoc
#    - cp -r target/site/apidocs/. public/
#  artifacts:
#    paths:
#      - public
#    expire_in: 1 day
#  only:
#    - master
